### ISSUE TITLE
It doesn't work on windows

### ISSUE THREAD

**Issue by tifDev** [kek/sublime-expand-selection-to-quotes#13]

**Comment by kek** [comment]
I would be happy for someone to confirm or disprove this as I don't have a windows computer readily available. Is it just the shortcut that's not working? Or the plugin entirely? Does it work if you invoke the command via the menu (Selection -> Expand Selection to Quotes)?

**Comment by brian6932** [comment]
It works for me on Windows 10 🤷

**Comment by kek** [comment]
That's great @brian6932 ! Thank you.
