### ISSUE TITLE
Only seems to work with code

### ISSUE THREAD

**Issue by Perkin5** [kek/sublime-expand-selection-to-quotes#9]
If I try to expand selection to quotes in a text element as opposed to a code element eg     <p>'select this text'</p>,     it doesn't seem to work. I get this in the console:      Info: scope 'text.html.basic ', score (0, 0).      Is that correct behaviour? I'm on Windows 7 and ST3

**Comment by kek** [comment]
I can't reproduce this. What's type of file is it? And can you provide the contents of it?

**Comment by Perkin5** [comment]
I set up a file called test.php with the following contents:
<?php echo 'select this text'; ?>
'select this text'

If I click between the quotes in the top line I can expand to quotes perfectly.
If I click between quotes in the second line nothing happens.
BTW the console message for the correct (top line) behaviour is:
Info: scope 'text.html.basic source.php.embedded.block.html string.quoted.single.php meta.string-contents.quoted.single.php ', score (512, 512)

**Comment by kek** [comment]
I created a file similar to your example, and it worked. It has to be some kind of environmental difference.

Perhaps it's some kind of conflict with some other plugin? Could it be the same thing as discussed here? https://github.com/kek/sublime-expand-selection-to-quotes/issues/8#issuecomment-147076119

**Comment by Perkin5** [comment]
Thanks for the response.

I enabled

sublime.log_commands(True)

and the console showed the command initiated correctly. Incidentally, in 
the thread you sent me the link for, the command was 
'expand_selection_to_quotes' whereas I am using 'select_quoted' - am I 
right?

I also had another package installed called ChangeQuotes so I 
uninstalled that but it seemed to make no difference.

In case it helps have the following packages installed: Browser Refresh, 
CSS3, Emmett, Yayaku, HTML Boilerplate, Laravel Blade highlighter, 
Package Control, Package Resource Viewer, PyV8, Select Quoted, 
SidebarEnhancements, Sublime-autoprefixer-master, Tag

**Comment by kek** [comment]
When I run `sublime.log_commands(True)` and then press `Ctrl+'` in the file, the console output is `command: expand_selection_to_quotes`. select_quoted is another plugin which seems to have the same purpose and the same default keybinding.

**Comment by Perkin5** [comment]
Oh! How confusing.

So I have uninstalled the package SelectQuoted but Package Control seems 
to be unable to find Expand Selection to Quotes. Am I searching for the 
wrong string?

**Comment by kek** [comment]
This plugin was listed in Package Control as supporting only ST2 until yesterday. Can you check again?

**Comment by Perkin5** [comment]
Way to go!

Installed and works like a charm. Thanks so much for taking the time. I 
will use this so much!

Mike
